# Generated by Django 5.2.15 on 2026-08-11 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0002_alter_teammember_team'),
        ('tournaments', '0004_tournament_champion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentregistration',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solo_tournament_registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tournamentregistration',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_registrations', to='teams.team'),
        ),
        migrations.RemoveConstraint(
            model_name='tournamentregistration',
            name='unique_team_registration',
        ),
        migrations.AddConstraint(
            model_name='tournamentregistration',
            constraint=models.UniqueConstraint(condition=models.Q(('team__isnull', False)), fields=('tournament', 'team'), name='unique_team_registration'),
        ),
        migrations.AddConstraint(
            model_name='tournamentregistration',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('tournament', 'user'), name='unique_user_solo_registration'),
        ),
    ]
