# Generated by Django 5.2.15 on 2026-08-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_tournamentregistration_user_alter_tournamentregistration_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='logo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='games/logos/'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='banner',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='tournaments/banners/'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='cover_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='tournaments/covers/'),
        ),
    ]
