# Generated by Django 5.2 on 2026-08-18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_alter_game_logo_alter_tournament_banner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_bye',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='next_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_matches', to='tournaments.match'),
        ),
        migrations.AddField(
            model_name='match',
            name='next_match_slot',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
