# Generated by Django 5.2.15 on 2026-08-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_alter_teammember_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='teams/logos/'),
        ),
    ]
