# Generated by Django on 2026-08-16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
        ('teams', '0003_alter_team_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='game',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='teams',
                to='tournaments.game'
            ),
        ),
    ]
