# Generated by Django 5.2.15 on 2026-07-22 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('teams', '0002_alter_teammember_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='team_invitation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='teams.teaminvitation'),
        ),
    ]
